- name: install and run nginx
  hosts: mongodb
  become: yes
  tasks:
  - name: install NGINX
    ansible.builtin.yum:
     name: nginx
     state: installed
  - name: statr nginx
    ansible.builtin.service:
     name: nginx
     state: started
